apiVersion: v1
kind: Namespace
metadata:
  name: nats-io
---
apiVersion: v1
data:
  nats.conf: |
    # PID file shared with configuration reloader.
    pid_file: "/var/run/nats/nats.pid"

    http: 8222
    server_name: $POD_NAME

    jetstream: {
        max_mem: 1Gi
        store_dir: /data/

        max_file: 126Gi
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/version: 2.3.4
  name: nats-config
  namespace: nats-io
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/version: 2.3.4
  name: nats
  namespace: nats-io
spec:
  ports:
  - appProtocol: tcp
    name: client
    port: 4222
  - appProtocol: tcp
    name: monitor
    port: 8222
  - appProtocol: http
    name: metrics
    port: 7777
  selector:
    app.kubernetes.io/name: nats
    app.kubernetes.io/version: 2.3.4
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/version: 2.3.4
  name: nats-mgmt
  namespace: nats-io
spec:
  clusterIP: None
  ports:
  - appProtocol: tls
    name: cluster
    port: 6222
  selector:
    app.kubernetes.io/name: nats
    app.kubernetes.io/version: 2.3.4
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/version: 2.3.4
  name: nats
  namespace: nats-io
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
      app.kubernetes.io/version: 2.3.4
  serviceName: nats-mgmt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nats
        app.kubernetes.io/version: 2.3.4
    spec:
      containers:
      - command:
        - nats-server
        - --config
        - /etc/nats-config/nats.conf
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_ADVERTISE
          value: $(POD_NAME).nats-mgmt.$(POD_NAMESPACE).svc.cluster.local.
        image: nats:alpine
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - nats-server -sl=ldm=/var/run/nats/nats.pid && /bin/sleep 60
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
        name: nats
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 7422
          name: leafnodes
        - containerPort: 7522
          name: gateways
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        - containerPort: 7777
          name: metrics
        readinessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /etc/nats-config
          name: config-volume
        - mountPath: /var/run/nats
          name: pid
        - mountPath: /data/
          name: nats-js-pvc
      - command:
        - nats-server-config-reloader
        - -pid
        - /var/run/nats/nats.pid
        - -config
        - /etc/nats-config/nats.conf
        image: natsio/nats-server-config-reloader:0.6.2
        imagePullPolicy: IfNotPresent
        name: reloader
        resources: {}
        volumeMounts:
        - mountPath: /etc/nats-config
          name: config-volume
        - mountPath: /var/run/nats
          name: pid
      shareProcessNamespace: true
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          name: nats-config
        name: config-volume
      - emptyDir: {}
        name: pid
      - emptyDir: {}
        name: nats-js-pvc
