/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	messagingv1alpha1 "knative.dev/eventing-natss/pkg/apis/messaging/v1alpha1"
)

// NatsJetStreamChannelLister helps list NatsJetStreamChannels.
// All objects returned here must be treated as read-only.
type NatsJetStreamChannelLister interface {
	// List lists all NatsJetStreamChannels in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*messagingv1alpha1.NatsJetStreamChannel, err error)
	// NatsJetStreamChannels returns an object that can list and get NatsJetStreamChannels.
	NatsJetStreamChannels(namespace string) NatsJetStreamChannelNamespaceLister
	NatsJetStreamChannelListerExpansion
}

// natsJetStreamChannelLister implements the NatsJetStreamChannelLister interface.
type natsJetStreamChannelLister struct {
	listers.ResourceIndexer[*messagingv1alpha1.NatsJetStreamChannel]
}

// NewNatsJetStreamChannelLister returns a new NatsJetStreamChannelLister.
func NewNatsJetStreamChannelLister(indexer cache.Indexer) NatsJetStreamChannelLister {
	return &natsJetStreamChannelLister{listers.New[*messagingv1alpha1.NatsJetStreamChannel](indexer, messagingv1alpha1.Resource("natsjetstreamchannel"))}
}

// NatsJetStreamChannels returns an object that can list and get NatsJetStreamChannels.
func (s *natsJetStreamChannelLister) NatsJetStreamChannels(namespace string) NatsJetStreamChannelNamespaceLister {
	return natsJetStreamChannelNamespaceLister{listers.NewNamespaced[*messagingv1alpha1.NatsJetStreamChannel](s.ResourceIndexer, namespace)}
}

// NatsJetStreamChannelNamespaceLister helps list and get NatsJetStreamChannels.
// All objects returned here must be treated as read-only.
type NatsJetStreamChannelNamespaceLister interface {
	// List lists all NatsJetStreamChannels in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*messagingv1alpha1.NatsJetStreamChannel, err error)
	// Get retrieves the NatsJetStreamChannel from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*messagingv1alpha1.NatsJetStreamChannel, error)
	NatsJetStreamChannelNamespaceListerExpansion
}

// natsJetStreamChannelNamespaceLister implements the NatsJetStreamChannelNamespaceLister
// interface.
type natsJetStreamChannelNamespaceLister struct {
	listers.ResourceIndexer[*messagingv1alpha1.NatsJetStreamChannel]
}
